### ISSUE TITLE
Angular-meteor not recognised

### ISSUE THREAD

**Issue by ap149** [idanwe/ionic-cli-meteor-whatsapp-tutorial#1]
Hi - following the tutorial, installing meteor-client-side and angular-meteor seem to throw some version dependency conflicts I think? 

Have tried resolving but keep getting the error: "Module 'angular-meteor' is not available!". Any suggestions please?

Thanks

**Comment by idanwe** [comment]
@ap149  Thanks for noticed.
We are working on solving it, hope it will be solved later today

**Comment by ap149** [comment]
No problem - great. The following seems to be a problem (line 17 in angular-meteor/dist/angular-meteor.bundle.js):

var MongoID = Package['mongo-id'].MongoID;

Don't know whether that's something to do with it?

**Comment by idanwe** [comment]
@ap149 angular-meteor released 1.0.3 and now it fixed
