### ISSUE TITLE
ECMAScript problem goes on

### ISSUE THREAD

**Issue by elmor34** [idanwe/ionic-cli-meteor-whatsapp-tutorial#4]
Problem goes on although issue closed.
Regards.

_Uncaught TypeError: Cannot read property 'ECMAScript' of undefined(anonymous function) @ angular-meteor.bundle.js:1142(anonymous function) @ angular-meteor.bundle.js:1422
ionic.bundle.js:8895 Uncaught Error: [$injector:modulerr] Failed to instantiate module whatsapp due to:
Error: [$injector:modulerr] Failed to instantiate module angular-meteor due to:
Error: [$injector:nomod] Module 'angular-meteor' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument._

So selecting any of the following options do not help 

_Unable to find a suitable version for angular, please choose one:
    1) angular#1.4.3 which resolved to 1.4.3 and is required by angular-animate#1.4.3, angular-sanitize#1.4.3, ionic#1.1.0
    2) angular#1.4.4 which resolved to 1.4.4 and is required by angular-meteor#1.0.7
    3) angular#>=1.2.0 <1.5.0 which resolved to 1.4.7 and is required by angular-moment#0.10.3
    4) angular#>= 1.0.8 which resolved to 1.4.7 and is required by angular-ui-router#0.2.13_

Any advice to overcome

**Comment by Urigo** [comment]
What version of angular-meteor are you using?

**Comment by elmor34** [comment]
Thanks for prompt reply. 
It worked with correcting following line in bower.json as :

**"angular-meteor": "~1.2.0",**    

Actually I did the same in just after you closed the previous issue, and it was asking 4 options,
now it's asking 3 options. And this time worked.

If you can update this in bower.json then we would not disturb you. :+1: 
Thanks...

**Comment by idanwe** [comment]
@elmor34 done! thank you
