### ISSUE TITLE
angular-meteor-auth  no exist?

### ISSUE THREAD

**Issue by mjsorribas** [idanwe/ionic-cli-meteor-whatsapp-tutorial#7]
I donwload the proyect but i can't run , this is the error:
http://localhost:8100/lib/angular-meteor/dist/angular-meteor-auth.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
i don't find this file in the project.
And the other error is " Uncaught ReferenceError: Mongo is not defined"

**Comment by strangemodern** [comment]
I've been having the same 404 issue as well.

I even installed the angular-meteor-auth package.
Now I get: Accounts.user is not a function. (In 'Accounts.user()', 'Accounts.user' is undefined)

@Urigo what should we update?

**Comment by Urigo** [comment]
THIS REPO IS DEPRECATED

The repo has been moved to https://github.com/Urigo/IonicCLI-Meteor-WhatsApp.
